version: "3.9"

services:
  thesis-app:
    image: 'thesis-app'
    build:
      context: .
    depends_on:
      - thesis_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://thesis_db:5432/service_based_assessment_db
      - SPRING_DATASOURCE_USERNAME=service_based_assessment_user
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_GENERATE_DDL=true
      - SPRING_JPA_SHOW_DDL=true
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=*
    ports:
      - '8080:8080'

  thesis_db:
    image: postgres
    container_name: thesis_db
    environment:
      POSTGRES_USER: service_based_assessment_user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: service_based_assessment_db
    ports:
      - '5436:5432'

#  pgadmin:
#    image: 'dpage/pgadmin4:latest'
#    container_name: pgadmin
#    environment:
#      PGADMIN_DEFAULT_EMAIL: kon@local.com
#      PGADMIN_DEFAULT_PASSWORD: 123456
#    ports:
#      - '5000:80'
#
#  text_classification:
#    build:
#      context: ./text classification/.
#    #    image: 'text_classification_flask'
#    container_name: text_classification_flask
#    ports:
#      - '6000:5000'
