variables:
  isExternalServiceAvailable: false
  sba:
    #    url: http://172.23.0.3:8080
    url: http://localhost:8080
    test_repo1:
      url: https://github.com/niekwit/pyseqtools
      branch: main
    test_repo2:
      url: https://github.com/donnemartin/system-design-primer
      branch: master
  text_classification:
    url: http://192.168.1.11:5000/
  github_api:
    url: https://api.github.com/repos/

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/service_based_assessment_db
    username: service_based_assessment_user
    password: 123456
  jpa:
#    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: create-drop
        schema_update:
          unique_constraint_strategy: RECREATE_QUIETLY
        generate-ddl: true
