variables:
  sba:
    url: http://195.251.210.147:8585
    gitURL: https://github.com/niekwit/pyseqtools
    gitURL2: https://github.com/donnemartin/system-design-primer
  text_classification:
    url: http://192.168.1.11:5000/
  github_api:
    url: https://api.github.com/repos/

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/service_based_assessment_db
    username: service_based_assessment_user
    password: 123456
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: create-drop
        schema_update:
          unique_constraint_strategy: RECREATE_QUIETLY
        generate-ddl: true
