#spring:
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create-drop
#  datasource:
#    url: jdbc:po://localhost:3306/springboot
#    username: root
#    password:

variables:
  sba:
#    url: http://195.251.210.147:8282
    gitURL: https://github.com/niekwit/pyseqtools
    url: 127.0.0.1:8081